@startuml
actor actor_User_579e9aae81 as "User"
entity server_WebServer_f2eb7a3ff7 as "Web Server"
database datastore_SQLDatabase_d2006ce1bb as "SQL Database"

actor_User_579e9aae81 -> server_WebServer_f2eb7a3ff7: (1) User enters comments (*)
note left
bbb
end note
server_WebServer_f2eb7a3ff7 -> datastore_SQLDatabase_d2006ce1bb: (2) Insert query with comments
note left
ccc
end note
datastore_SQLDatabase_d2006ce1bb -> server_WebServer_f2eb7a3ff7: (3) Retrieve comments
server_WebServer_f2eb7a3ff7 -> actor_User_579e9aae81: (4) Show comments (*)
@enduml
